name: benchmarks
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install qemu-system
        run: |
          sudo apt update
          sudo apt install -y qemu-system
      - name: Install dependencies
        run:  pip3 install -r requirements.txt
      - name: Install Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.8.0
        with:
          release: 13.2.Rel1
      # cycle counts are not meaningful, but at least we can make sure benchmarks compile and run
      - name: Benchmarks (mps2-an386)
        run: ./benchmarks.py -p mps2-an386