name: testvectors
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-all:
    strategy:
      matrix:
        arm-gcc-release: [14.2.Rel1, 13.3.Rel1, 12.3.Rel1]
    runs-on: ubuntu-latest
    name: testvectors (gcc ${{ matrix.arm-gcc-release }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install qemu-system
        run: |
          sudo apt update
          sudo apt install -y qemu-system
      - name: Install dependencies
        run:  pip3 install -r requirements.txt
      - name: Install Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.10.0
        with:
          release: ${{ matrix.arm-gcc-release }}
      - name: Testvectors (mps2-an386)
        run: ./testvectors.py -p mps2-an386